# Generated by Django 5.2.7 on 2025-11-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0002_purchase_created_at_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_games',
            new_name='wishlist_games',
        ),
    ]
