# Generated by Django 5.2.7 on 2025-11-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0003_rename_favorite_games_user_wishlist_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist_games',
        ),
    ]
