# Generated by Django 5.2.7 on 2025-11-24 22:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0006_game_cover_image_url_game_rawg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rawg_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(upload_to='game_covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game_store_app.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
